spring:
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/zhiliao?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      platform: mysql
      druid:
        # 下面为连接池的补充设置，应用到上面所有数据源中
        # 初始化大小，最小，最大
        initial-size: 1
        min-idle: 1
        max-active: 10
        # 配置获取连接等待超时的时间
        max-wait: 30000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        time-between-eviction-runs-millis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        min-evictable-idle-time-millis: 1800000
        max-evictable-idle-time-millis: 25200000
        validation-query: SELECT 1
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        pool-prepared-statements: true
        max-open-prepared-statements: 20
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        use-global-data-source-stat: true
        # 默认开启，当前已开启
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
        # 默认关闭，需手动开启，当前已开启
        slf4j:
          enabled: true
          connection-log-enabled: false
          statement-sql-format-option:
            upp-case: true
            pretty-format: false
          statement-executable-sql-log-enable: true
          result-set-log-enabled: false
        # 默认关闭，需手动开启，当前已开启
        wall:
          enabled: true
          log-violation: true
          throw-exception: false
          config:
            delete-where-none-check: true
        # 默认关闭，需手动开启，当前已关闭
        config:
          enabled: false
        # 默认关闭，需手动开启，当前已关闭
        web-stat:
          enabled: false
        # 默认关闭，需手动开启，当前已关闭
        aop-stat:
          enabled: false
        # 默认关闭，需手动开启，当前已关闭
        stat-view-servlet:
          enabled: true

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml